Set section length dynamically
tell-k/django-modelsdoc pull request #6
Opened 2018-01-28 08:50 UTC by wanshot

Hi  tell-k
In the case of long model verbose, syntax error of reStructuredText will result.

I set the section length dynamically.

However, I used wcwidth for this fix, but if you do not want to rely on external libraries, reject it

2018-01-31 03:36 UTC, tell-k requested changes
@wanshot 

First of all thanks for your nice PR.

I have a question for you.
Why shold we need `wcwdith`?

I do not think that an exact character width is necessary. By converting to bytes, you can get a length longer than the exact character width. That's enough.

```python
# py3
from django.utils.encoding import force_bytes
from wcwidth import wcswidth

print(len(force_bytes('日本語'))) # => 9 (This is enough length).
print(wcswidth('日本語'))         # => 6
```

In other words, it can be a simpler implementation.
Please try this implementaion and modfied your PR.

https://gist.github.com/tell-k/a6b7a2bfb15952fa898c9dcda95efba7

If this is not good, please report again.
Thx for your help :)

2018-01-31 03:36 UTC, tell-k commented on tox.ini
> +    wcwidth
This line isn't needed.  Because `wcwidth` exists in install_requires of setup.py.  you should write only the testing library here.

2018-01-31 15:47 UTC, wanshot commented
Thanks for the reply:satisfied:

Certainly precise number of characters was not necessary.

The suggested modification is better than what I thought. We will consider it as a reference.
I fix it and PR again！

2018-01-31 16:02 UTC, tell-k commented
> I fix it and PR again！
yeah!
i'm look forward to your next PR. 

thx.

2018-02-06 09:02 UTC, wanshot commented
I will be glad if you look fixed at your convenience!

2018-02-08 12:13 UTC, merged

2018-02-08 12:16 UTC, tell-k commented
@wanshot Sorry too late my reply.  Thank you for your help.

2018-02-08 13:53 UTC, tell-k commented
I've just released v1.9.0 https://pypi.python.org/pypi/django-modelsdoc/0.1.9

2018-02-08 17:07 UTC, wanshot commented
:tada: